export type {
	Pigment,
	PuzzleGrid,
	PuzzleTemplate,
	PuzzleConfig,
	PuzzlePack,
	PackDefinition
} from './types.js';
export {
	PIGMENT_HEX,
	PIGMENT_NAME,
	MONO_FLIP_SOLVED_VALUE,
	PIGMENT_CLEAR_SOLVED_VALUE
} from './types.js';
export { packs, getPackBySlug, getPuzzleById, getNextPuzzleId, getPackPuzzleCount } from './packs.js';
export {
	applyTemplate,
	isSolved,
	isPuzzleSolved,
	isPuzzleComplete,
	allTemplatesUsed,
	fullTemplateUsedMask,
	rotateRight,
	orientTemplate,
	areAllElementsOne,
	getValidPositions,
	getCenteredPosition
} from './PuzzleFunctions.js';
export {
	getTemplateCellPigment,
	distinctPigmentsInTemplate,
	isMultiColoredTemplate,
	isTemplateCellActive,
	maskToUnifiedShape,
	normalizeTemplate,
	migrateSplitTemplate
} from './templatePigment.js';
export { overwriteWithSubmatrix, getSubmatrix, elementWiseOperation } from './MatrixFunctions.js';
export { normalizePuzzleConfig, isMonochromeFlipPuzzle } from './puzzleNormalize.js';
export { serializePuzzleForStorage, parseStoredPuzzle } from './storedPuzzle.js';
export { getValidPuzzle } from './PuzzleValidator.js';
export type { HintMove } from './PuzzleHint.js';
export { findHintMove } from './PuzzleHint.js';
export type { GeneratedPuzzleConfig, DifficultyPreset, GeneratorConfig } from './PuzzleGenerator.js';
export { gridToKey, canonicalizeGrid, getDistinctRotations } from './puzzleGrid.js';
export {
	generateVerifiedPuzzle,
	solveMinMoves,
	solveMinMovesGridOnly,
	DIFFICULTY_PRESETS,
	monoGeneratorConfig,
	pigmentGeneratorConfig
} from './PuzzleGenerator.js';
export {
	MIN_TEMPLATE_ACTIVE_CELLS,
	countActiveCells,
	templateMeetsMinActiveCells
} from './templateShape.js';
export {
	MIN_TEMPLATES_PER_PIGMENT_MULTI,
	countTemplatesByPigment,
	isMultiPigmentPuzzle,
	meetsMinTemplatesPerPigment,
	minTemplatesPerPigmentForAllowed,
	requiredTemplateCount,
	validateMultiPigmentTemplateCounts
} from './pigmentTemplates.js';
export {
	canonicalPuzzleKey,
	canonicalTemplateKey,
	isAutoGeneratedPack,
	AUTO_GENERATED_PACK_SLUGS
} from './puzzleCanonical.js';
export {
	PRODUCTION_PACK_SLUGS,
	isProductionPack,
	type ProductionPackSlug
} from './productionPacks.js';
export {
	FIRST_STEPS_SLUG,
	FIRST_STEPS_CONCEPTS,
	getFirstStepsConcept
} from './puzzles/firstSteps.js';
export { archivedFirstStepsPuzzle5 } from './puzzles/firstStepsArchive.js';
