import { describe, it, expect } from 'vitest';
import {
	MIN_TEMPLATE_ACTIVE_CELLS,
	countActiveCells,
	templateMeetsMinActiveCells,
	is2x2Shape,
	mono2x2TemplateIsFullyFilled,
	templateMeetsMonoSquareFillRule,
	constrainMonoTemplateSizes,
	FULL_2X2_MONO_ACTIVE_CELLS
} from './templateShape.js';
import { canonicalPuzzleKey, isAutoGeneratedPack } from './puzzleCanonical.js';
import { evaluatePuzzleDifficulty } from './puzzleDifficulty.js';
import { buildGeneratorConfig } from './packGeneration.js';
import { packUsesMonoSquareTemplateGeneration } from './packGenerationSpecs.js';
import { buildGeneratorTemplates } from './PuzzleGenerator.js';
import { packs } from './packs.js';

describe('templateShape', () => {
	it('requires at least two active cells', () => {
		expect(templateMeetsMinActiveCells([[1, 0], [1, 1]])).toBe(true);
		expect(templateMeetsMinActiveCells([[1]])).toBe(false);
		expect(MIN_TEMPLATE_ACTIVE_CELLS).toBe(2);
	});

	it('requires full 2×2 mono square templates', () => {
		expect(FULL_2X2_MONO_ACTIVE_CELLS).toBe(4);
		expect(is2x2Shape([[1, 1], [1, 1]])).toBe(true);
		expect(mono2x2TemplateIsFullyFilled([[1, 1], [1, 1]])).toBe(true);
		expect(mono2x2TemplateIsFullyFilled([[1, 0], [1, 1]])).toBe(false);
		expect(templateMeetsMonoSquareFillRule(2, [[1, 0], [0, 1]])).toBe(false);
		expect(templateMeetsMonoSquareFillRule(3, [[1, 0], [1, 1], [0, 1]])).toBe(true);
	});

	it('allows at most one 2×2 slot in mono template size lists', () => {
		expect(constrainMonoTemplateSizes([2, 2, 3])).toEqual([2, 3, 3]);
		expect(constrainMonoTemplateSizes([3, 2, 2])).toEqual([3, 2, 3]);
	});
});

describe('PuzzleGenerator mono 2×2 rule', () => {
	it('buildGeneratorTemplates never emits partial 2×2 mono stencils', () => {
		for (let attempt = 0; attempt < 30; attempt++) {
			const templates = buildGeneratorTemplates(
				buildGeneratorConfig({ kind: 'mono', targetMinMoves: 3, templateSizes: [2, 3, 3] })
			);
			expect(templates).not.toBeNull();
			for (const template of templates!) {
				if (is2x2Shape(template.shape)) {
					expect(mono2x2TemplateIsFullyFilled(template.shape)).toBe(true);
				}
			}
		}
	});
});

describe('auto pack quality', () => {
	it('auto-generated packs use canonical keys without duplicates', () => {
		const seen = new Set<string>();
		for (const pack of packs) {
			if (!isAutoGeneratedPack(pack.slug)) continue;
			for (const cfg of Object.values(pack.puzzles)) {
				const key = canonicalPuzzleKey(cfg);
				expect(seen.has(key), `${pack.slug} duplicate`).toBe(false);
				seen.add(key);
			}
		}
	});

	it('mono square-template packs use full 2×2 stencils when present', () => {
		for (const pack of packs) {
			if (!packUsesMonoSquareTemplateGeneration(pack.slug)) continue;
			for (const cfg of Object.values(pack.puzzles)) {
				for (const template of cfg.templates) {
					if (is2x2Shape(template.shape)) {
						expect(mono2x2TemplateIsFullyFilled(template.shape)).toBe(true);
					}
				}
			}
		}
	});

	it('auto-generated templates have at least two active cells', () => {
		for (const pack of packs) {
			if (!isAutoGeneratedPack(pack.slug)) continue;
			for (const cfg of Object.values(pack.puzzles)) {
				for (const template of cfg.templates) {
					expect(countActiveCells(template.shape)).toBeGreaterThanOrEqual(
						MIN_TEMPLATE_ACTIVE_CELLS
					);
				}
			}
		}
	});

	it(
		'grid-4x4-dev pack stores composite difficulty in non-decreasing order',
		() => {
			const pack = packs.find((entry) => entry.slug === 'grid-4x4-dev');
			expect(pack).toBeDefined();

			const composites = Object.values(pack!.puzzles).map((cfg) => {
				const report = evaluatePuzzleDifficulty(cfg);
				expect(report).not.toBeNull();
				return report!.compositeDifficulty;
			});
			expect(composites).toHaveLength(30);
			for (let i = 1; i < composites.length; i++) {
				expect(composites[i]).toBeGreaterThanOrEqual(composites[i - 1]);
			}
		},
		60_000
	);

	it('intro-pack puzzle 1 meets minimum template size', () => {
		const intro1 = packs.find((p) => p.slug === 'intro-pack')!.puzzles[1];
		expect(countActiveCells(intro1.templates[0].shape)).toBeGreaterThanOrEqual(2);
	});
});
