/**
 * Canonical puzzle identity for deduplication (start grid + normalized templates).
 */

import { canonicalizeGrid, gridToKey } from './puzzleGrid.js';
import { isMonochromeFlipPuzzle } from './puzzleNormalize.js';
import { getDistinctTemplateOrientations, pigmentLayerKey } from './templatePigment.js';
import type { PuzzleConfig, PuzzleTemplate } from './types.js';

/** Slugs for packs produced by PACK_GENERATION_SPECS (no imports from packGeneration). */
export const AUTO_GENERATED_PACK_SLUGS = [
	'tutorial-auto',
	'easy-auto',
	'medium-auto',
	'hard-auto',
	'expert-auto',
	'color-spectrum',
	'chromatic-ascent',
	'color-ladder',
	'grid-4x4-dev'
] as const;

export function isAutoGeneratedPack(slug: string): boolean {
	return (AUTO_GENERATED_PACK_SLUGS as readonly string[]).includes(slug);
}

export function canonicalTemplateKey(template: PuzzleTemplate): string {
	const orientations = getDistinctTemplateOrientations(template);
	let best = '';
	for (const oriented of orientations) {
		const key = `${pigmentLayerKey(oriented)}:${oriented.shape.map((row) => row.join('')).join('|')}`;
		if (!best || key < best) best = key;
	}
	return best;
}

/** Stable key for a full puzzle config — used for cross-pack dedup. */
export function canonicalPuzzleKey(config: PuzzleConfig): string {
	const gridKey = isMonochromeFlipPuzzle(config)
		? canonicalizeGrid(config.startState)
		: gridToKey(config.startState);
	const templateKeys = config.templates.map(canonicalTemplateKey).sort().join(';');
	return `${gridKey}::${templateKeys}::sv${config.solvedValue}`;
}
