import { describe, it, expect } from 'vitest';
import {
	MIN_TEMPLATE_ACTIVE_CELLS,
	countActiveCells,
	templateMeetsMinActiveCells
} from './templateShape.js';
import { canonicalPuzzleKey, isAutoGeneratedPack } from './puzzleCanonical.js';
import { packs } from './packs.js';

describe('templateShape', () => {
	it('requires at least two active cells', () => {
		expect(templateMeetsMinActiveCells([[1, 0], [1, 1]])).toBe(true);
		expect(templateMeetsMinActiveCells([[1]])).toBe(false);
		expect(MIN_TEMPLATE_ACTIVE_CELLS).toBe(2);
	});
});

describe('auto pack quality', () => {
	it('auto-generated packs use canonical keys without duplicates', () => {
		const seen = new Set<string>();
		for (const pack of packs) {
			if (!isAutoGeneratedPack(pack.slug)) continue;
			for (const cfg of Object.values(pack.puzzles)) {
				const key = canonicalPuzzleKey(cfg);
				expect(seen.has(key), `${pack.slug} duplicate`).toBe(false);
				seen.add(key);
			}
		}
	});

	it('auto-generated templates have at least two active cells', () => {
		for (const pack of packs) {
			if (!isAutoGeneratedPack(pack.slug)) continue;
			for (const cfg of Object.values(pack.puzzles)) {
				for (const template of cfg.templates) {
					expect(countActiveCells(template.shape)).toBeGreaterThanOrEqual(
						MIN_TEMPLATE_ACTIVE_CELLS
					);
				}
			}
		}
	});

	it('intro-pack puzzle 1 meets minimum template size', () => {
		const intro1 = packs.find((p) => p.slug === 'intro-pack')!.puzzles[1];
		expect(countActiveCells(intro1.templates[0].shape)).toBeGreaterThanOrEqual(2);
	});
});
