import type { PackDefinition } from '../types.js';
import type { SimpleSolutionMove } from '../simplePuzzleGeneration.js';

/**
 * Dev pack — 3×3 mono, 3 canonical templates, 3 moves.
 * Generated by scripts/generate-simple-dev-pack.ts.
 */
export const simpleMonoDevPack: PackDefinition = {
	name: 'Simple Mono Dev',
	slug: 'simple-mono-dev',
	access: 'free',
	puzzles: {
	1: {
		"startState": [
			[
				1,
				1,
				1
			],
			[
				1,
				0,
				0
			],
			[
				1,
				0,
				1
			]
		],
		"templates": [
			{
				"shape": [
					[
						1,
						0,
						1
					],
					[
						0,
						0,
						1
					],
					[
						1,
						1,
						0
					]
				]
			},
			{
				"shape": [
					[
						1,
						0,
						1
					],
					[
						0,
						1,
						1
					],
					[
						0,
						0,
						0
					]
				]
			},
			{
				"shape": [
					[
						0,
						1,
						1
					],
					[
						1,
						1,
						1
					],
					[
						0,
						0,
						0
					]
				]
			}
		],
		"solvedValue": 0
	},
	2: {
		"startState": [
			[
				1,
				1,
				1
			],
			[
				0,
				0,
				0
			],
			[
				0,
				1,
				0
			]
		],
		"templates": [
			{
				"shape": [
					[
						0,
						1,
						1
					],
					[
						1,
						0,
						1
					],
					[
						0,
						0,
						0
					]
				]
			},
			{
				"shape": [
					[
						0,
						1,
						1
					],
					[
						0,
						0,
						0
					],
					[
						1,
						1,
						0
					]
				]
			},
			{
				"shape": [
					[
						1,
						1,
						0
					],
					[
						1,
						0,
						1
					],
					[
						0,
						0,
						0
					]
				]
			}
		],
		"solvedValue": 0
	},
	3: {
		"startState": [
			[
				1,
				1,
				1
			],
			[
				1,
				0,
				1
			],
			[
				0,
				1,
				0
			]
		],
		"templates": [
			{
				"shape": [
					[
						1,
						0,
						1
					],
					[
						1,
						1,
						0
					],
					[
						1,
						0,
						0
					]
				]
			},
			{
				"shape": [
					[
						1,
						0,
						1
					],
					[
						1,
						0,
						0
					],
					[
						1,
						1,
						0
					]
				]
			},
			{
				"shape": [
					[
						1,
						1,
						1
					],
					[
						1,
						1,
						1
					],
					[
						0,
						0,
						0
					]
				]
			}
		],
		"solvedValue": 0
	},
	4: {
		"startState": [
			[
				1,
				0,
				0
			],
			[
				1,
				1,
				0
			],
			[
				0,
				1,
				0
			]
		],
		"templates": [
			{
				"shape": [
					[
						0,
						0,
						1
					],
					[
						1,
						0,
						0
					],
					[
						1,
						0,
						0
					]
				]
			},
			{
				"shape": [
					[
						1,
						0,
						1
					],
					[
						0,
						1,
						0
					],
					[
						0,
						0,
						0
					]
				]
			},
			{
				"shape": [
					[
						0,
						1,
						1
					],
					[
						1,
						0,
						0
					],
					[
						0,
						1,
						0
					]
				]
			}
		],
		"solvedValue": 0
	},
	5: {
		"startState": [
			[
				0,
				1,
				0
			],
			[
				1,
				0,
				0
			],
			[
				1,
				1,
				1
			]
		],
		"templates": [
			{
				"shape": [
					[
						1,
						1,
						1
					],
					[
						0,
						1,
						0
					],
					[
						0,
						0,
						0
					]
				]
			},
			{
				"shape": [
					[
						0,
						0,
						0
					],
					[
						1,
						1,
						1
					],
					[
						0,
						0,
						0
					]
				]
			},
			{
				"shape": [
					[
						0,
						1,
						1
					],
					[
						0,
						0,
						0
					],
					[
						1,
						1,
						0
					]
				]
			}
		],
		"solvedValue": 0
	},
	6: {
		"startState": [
			[
				1,
				1,
				1
			],
			[
				1,
				0,
				1
			],
			[
				0,
				1,
				0
			]
		],
		"templates": [
			{
				"shape": [
					[
						0,
						0,
						0
					],
					[
						1,
						1,
						1
					],
					[
						0,
						0,
						0
					]
				]
			},
			{
				"shape": [
					[
						0,
						1,
						1
					],
					[
						1,
						0,
						1
					],
					[
						0,
						0,
						0
					]
				]
			},
			{
				"shape": [
					[
						0,
						0,
						1
					],
					[
						1,
						1,
						0
					],
					[
						0,
						0,
						0
					]
				]
			}
		],
		"solvedValue": 0
	},
	7: {
		"startState": [
			[
				1,
				1,
				0
			],
			[
				0,
				1,
				0
			],
			[
				0,
				1,
				0
			]
		],
		"templates": [
			{
				"shape": [
					[
						1,
						0,
						0
					],
					[
						0,
						1,
						1
					],
					[
						0,
						0,
						0
					]
				]
			},
			{
				"shape": [
					[
						1,
						1,
						1
					],
					[
						0,
						1,
						0
					],
					[
						0,
						0,
						0
					]
				]
			},
			{
				"shape": [
					[
						0,
						0,
						1
					],
					[
						0,
						1,
						0
					],
					[
						1,
						0,
						0
					]
				]
			}
		],
		"solvedValue": 0
	},
	8: {
		"startState": [
			[
				0,
				1,
				0
			],
			[
				0,
				1,
				1
			],
			[
				0,
				1,
				0
			]
		],
		"templates": [
			{
				"shape": [
					[
						1,
						0,
						1
					],
					[
						1,
						0,
						0
					],
					[
						1,
						0,
						0
					]
				]
			},
			{
				"shape": [
					[
						0,
						1,
						1
					],
					[
						0,
						1,
						0
					],
					[
						0,
						0,
						0
					]
				]
			},
			{
				"shape": [
					[
						1,
						0,
						1
					],
					[
						1,
						0,
						1
					],
					[
						0,
						1,
						0
					]
				]
			}
		],
		"solvedValue": 0
	},
	9: {
		"startState": [
			[
				1,
				0,
				1
			],
			[
				0,
				1,
				1
			],
			[
				1,
				1,
				1
			]
		],
		"templates": [
			{
				"shape": [
					[
						0,
						0,
						1
					],
					[
						1,
						1,
						1
					],
					[
						0,
						0,
						0
					]
				]
			},
			{
				"shape": [
					[
						0,
						0,
						1
					],
					[
						1,
						0,
						1
					],
					[
						1,
						0,
						0
					]
				]
			},
			{
				"shape": [
					[
						1,
						1,
						0
					],
					[
						0,
						0,
						1
					],
					[
						0,
						0,
						0
					]
				]
			}
		],
		"solvedValue": 0
	},
	10: {
		"startState": [
			[
				0,
				1,
				1
			],
			[
				1,
				1,
				0
			],
			[
				0,
				0,
				0
			]
		],
		"templates": [
			{
				"shape": [
					[
						1,
						1,
						1
					],
					[
						1,
						1,
						0
					],
					[
						0,
						1,
						0
					]
				]
			},
			{
				"shape": [
					[
						1,
						1,
						0
					],
					[
						0,
						0,
						1
					],
					[
						1,
						0,
						0
					]
				]
			},
			{
				"shape": [
					[
						1,
						1,
						1
					],
					[
						0,
						0,
						0
					],
					[
						1,
						0,
						0
					]
				]
			}
		],
		"solvedValue": 0
	}
	}
};

/** Solution move sets, keyed by puzzle id. Any application order solves the puzzle. */
export const simpleMonoDevSolutions: Record<number, SimpleSolutionMove[]> = {
	1: [
		{
			"templateIndex": 0,
			"rotation": 0,
			"row": 0,
			"col": 0
		},
		{
			"templateIndex": 1,
			"rotation": 1,
			"row": 0,
			"col": 0
		},
		{
			"templateIndex": 2,
			"rotation": 0,
			"row": 0,
			"col": 0
		}
	],
	2: [
		{
			"templateIndex": 2,
			"rotation": 3,
			"row": 0,
			"col": 0
		},
		{
			"templateIndex": 0,
			"rotation": 3,
			"row": 0,
			"col": 0
		},
		{
			"templateIndex": 1,
			"rotation": 0,
			"row": 0,
			"col": 0
		}
	],
	3: [
		{
			"templateIndex": 1,
			"rotation": 0,
			"row": 0,
			"col": 0
		},
		{
			"templateIndex": 0,
			"rotation": 0,
			"row": 0,
			"col": 0
		},
		{
			"templateIndex": 2,
			"rotation": 0,
			"row": 0,
			"col": 0
		}
	],
	4: [
		{
			"templateIndex": 0,
			"rotation": 1,
			"row": 0,
			"col": 0
		},
		{
			"templateIndex": 1,
			"rotation": 1,
			"row": 0,
			"col": 0
		},
		{
			"templateIndex": 2,
			"rotation": 0,
			"row": 0,
			"col": 0
		}
	],
	5: [
		{
			"templateIndex": 0,
			"rotation": 1,
			"row": 0,
			"col": 0
		},
		{
			"templateIndex": 2,
			"rotation": 0,
			"row": 0,
			"col": 0
		},
		{
			"templateIndex": 1,
			"rotation": 0,
			"row": 0,
			"col": 0
		}
	],
	6: [
		{
			"templateIndex": 0,
			"rotation": 0,
			"row": 0,
			"col": 0
		},
		{
			"templateIndex": 2,
			"rotation": 0,
			"row": 0,
			"col": 0
		},
		{
			"templateIndex": 1,
			"rotation": 3,
			"row": 0,
			"col": 0
		}
	],
	7: [
		{
			"templateIndex": 2,
			"rotation": 1,
			"row": 0,
			"col": 0
		},
		{
			"templateIndex": 0,
			"rotation": 3,
			"row": 0,
			"col": 0
		},
		{
			"templateIndex": 1,
			"rotation": 2,
			"row": 0,
			"col": 0
		}
	],
	8: [
		{
			"templateIndex": 0,
			"rotation": 3,
			"row": 0,
			"col": 0
		},
		{
			"templateIndex": 2,
			"rotation": 2,
			"row": 0,
			"col": 0
		},
		{
			"templateIndex": 1,
			"rotation": 3,
			"row": 0,
			"col": 0
		}
	],
	9: [
		{
			"templateIndex": 1,
			"rotation": 1,
			"row": 0,
			"col": 0
		},
		{
			"templateIndex": 2,
			"rotation": 3,
			"row": 0,
			"col": 0
		},
		{
			"templateIndex": 0,
			"rotation": 0,
			"row": 0,
			"col": 0
		}
	],
	10: [
		{
			"templateIndex": 1,
			"rotation": 1,
			"row": 0,
			"col": 0
		},
		{
			"templateIndex": 2,
			"rotation": 3,
			"row": 0,
			"col": 0
		},
		{
			"templateIndex": 0,
			"rotation": 2,
			"row": 0,
			"col": 0
		}
	]
};

/** Difficulty scores (total active cells across all solution moves), keyed by puzzle id. */
export const simpleMonoDevDifficulty: Record<number, number> = {
	1: 14,
	2: 12,
	3: 16,
	4: 10,
	5: 11,
	6: 10,
	7: 10,
	8: 12,
	9: 11,
	10: 14
};
