/**
 * Generate one or all registry packs into packs.ts.
 *
 * Run from app-template:
 *   npx tsx packages/game/scripts/generate-pack.ts --slug=color-spectrum
 *   npx tsx packages/game/scripts/generate-pack.ts --all-auto
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { canonicalPuzzleKey } from '../src/puzzleCanonical.js';
import { generatePackDefinition } from '../src/packGeneration.js';
import {
	COLOR_LADDER_PUZZLE_6,
	getAutoGeneratedPackSlugs,
	getPackGenerationSpec,
	PACK_GENERATION_SPECS
} from '../src/packGenerationSpecs.js';
import { packs } from '../src/packs.js';
import type { PackDefinition, PuzzleConfig } from '../src/types.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const packsPath = resolve(__dirname, '../src/packs.ts');

function parseArgs(): { slugs: string[] } {
	const args = process.argv.slice(2);
	if (args.includes('--all-auto')) {
		return { slugs: getAutoGeneratedPackSlugs() };
	}

	const slugArg = args.find((arg) => arg.startsWith('--slug='));
	if (slugArg) {
		return { slugs: [slugArg.slice('--slug='.length)] };
	}

	const slugIndex = args.indexOf('--slug');
	if (slugIndex !== -1 && args[slugIndex + 1]) {
		return { slugs: [args[slugIndex + 1]] };
	}

	console.error('Usage: generate-pack.ts --slug=<pack-slug> | --all-auto');
	console.error(`Known slugs: ${PACK_GENERATION_SPECS.map((s) => s.slug).join(', ')}`);
	process.exit(1);
}

function collectSeenKeys(excludeSlugs: Set<string>): Set<string> {
	const seen = new Set<string>();
	for (const pack of packs) {
		if (excludeSlugs.has(pack.slug)) continue;
		for (const cfg of Object.values(pack.puzzles)) {
			seen.add(canonicalPuzzleKey(cfg));
		}
	}
	return seen;
}

function writePacks(merged: PackDefinition[]) {
	const header = readFileSync(packsPath, 'utf8').split('export const packs')[0];
	const footer = readFileSync(packsPath, 'utf8').split('export function getPackBySlug')[1];

	writeFileSync(
		packsPath,
		`${header}export const packs: PackDefinition[] = ${JSON.stringify(merged, null, 2)};
export function getPackBySlug${footer}`,
		'utf8'
	);
}

function mergePacks(
	existing: PackDefinition[],
	generatedBySlug: Map<string, PackDefinition>,
	slugs: string[]
): PackDefinition[] {
	const slugSet = new Set(slugs);
	const allAuto = getAutoGeneratedPackSlugs();
	const isFullAutoRegen =
		slugs.length === allAuto.length && slugs.every((slug) => allAuto.includes(slug));

	if (isFullAutoRegen) {
		const manual = existing.filter((pack) => !slugSet.has(pack.slug));
		return [...slugs.map((slug) => generatedBySlug.get(slug)!), ...manual];
	}

	const merged = existing.map((pack) => generatedBySlug.get(pack.slug) ?? pack);
	for (const slug of slugs) {
		if (!existing.some((pack) => pack.slug === slug)) {
			merged.push(generatedBySlug.get(slug)!);
		}
	}
	return merged;
}

function applyPreservedPuzzles(
	slug: string,
	generated: PackDefinition,
	existing: PackDefinition | undefined
): void {
	if (slug !== 'color-ladder' || !existing) return;

	const preserved: Record<number, PuzzleConfig> = {
		5: existing.puzzles[5],
		6: COLOR_LADDER_PUZZLE_6
	};

	for (const [id, puzzle] of Object.entries(preserved)) {
		if (puzzle) {
			generated.puzzles[Number(id)] = puzzle;
		}
	}
}

function main() {
	const { slugs } = parseArgs();
	const excludeSlugs = new Set(slugs);
	const seenCanonicalKeys = collectSeenKeys(excludeSlugs);

	const generatedBySlug = new Map<string, PackDefinition>();
	for (const slug of slugs) {
		const spec = getPackGenerationSpec(slug);
		if (!spec) {
			throw new Error(`Unknown pack slug "${slug}". Add it to PACK_GENERATION_SPECS.`);
		}
		console.log(`Generating ${spec.name} (${slug})…`);
		const existing = packs.find((pack) => pack.slug === slug);
		const generated = generatePackDefinition(spec, seenCanonicalKeys);
		applyPreservedPuzzles(slug, generated, existing);
		generatedBySlug.set(slug, generated);
	}

	const merged = mergePacks(packs, generatedBySlug, slugs);

	writePacks(merged);
	console.log(
		`Updated ${generatedBySlug.size} pack(s); ${seenCanonicalKeys.size} unique canonical puzzles tracked.`
	);
}

main();
