/**
 * Generate a dev pack using the simplified generation system and write it
 * to packages/game/src/puzzles/simpleMonoDev.ts.
 *
 * Run from app-template:
 *   npx tsx packages/game/scripts/generate-simple-dev-pack.ts
 */

import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { generateSimplePuzzle, type SimpleGeneratedPuzzle, type SimplePackConfig } from '../src/simplePuzzleGeneration.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(__dirname, '../src/puzzles/simpleMonoDev.ts');

const PACK_CONFIG: SimplePackConfig = {
	puzzleSize: 3,
	templateSize: 3,
	minTemplates: 3,
	maxTemplates: 3,
	minMoveCount: 3,
	maxMoveCount: 3,
	allowedPigments: [1],
	requireMulticolorTemplate: false,
	requireEachTemplateUsedAtLeastOnce: true,
	minFilledCells: 3
};

const PUZZLE_COUNT = 10;

function generate(): SimpleGeneratedPuzzle[] {
	const puzzles: SimpleGeneratedPuzzle[] = [];
	let attempts = 0;
	while (puzzles.length < PUZZLE_COUNT) {
		attempts++;
		const result = generateSimplePuzzle(PACK_CONFIG);
		if (result) puzzles.push(result);
		if (attempts > PUZZLE_COUNT * 500) {
			throw new Error(`Failed to generate ${PUZZLE_COUNT} puzzles after ${attempts} attempts`);
		}
	}
	console.log(`Generated ${PUZZLE_COUNT} puzzles in ${attempts} total attempts.`);
	return puzzles;
}

function serialize(value: unknown): string {
	return JSON.stringify(value, null, '\t').replace(/\n/g, '\n\t');
}

function buildFileContent(puzzles: SimpleGeneratedPuzzle[]): string {
	const puzzleEntries = puzzles
		.map((p, i) => {
			const id = i + 1;
			const config = {
				startState: p.config.startState,
				templates: p.config.templates,
				solvedValue: p.config.solvedValue
			};
			return `\t${id}: ${serialize(config)}`;
		})
		.join(',\n');

	const solutionEntries = puzzles
		.map((p, i) => {
			const id = i + 1;
			return `\t${id}: ${serialize(p.solution)}`;
		})
		.join(',\n');

	const difficultyEntries = puzzles
		.map((p, i) => `\t${i + 1}: ${p.difficulty}`)
		.join(',\n');

	return `import type { PackDefinition } from '../types.js';
import type { SimpleSolutionMove } from '../simplePuzzleGeneration.js';

/**
 * Dev pack — 3×3 mono, 3 canonical templates, 3 moves.
 * Generated by scripts/generate-simple-dev-pack.ts.
 */
export const simpleMonoDevPack: PackDefinition = {
\tname: 'Simple Mono Dev',
\tslug: 'simple-mono-dev',
\taccess: 'free',
\tpuzzles: {
${puzzleEntries}
\t}
};

/** Solution move sets, keyed by puzzle id. Any application order solves the puzzle. */
export const simpleMonoDevSolutions: Record<number, SimpleSolutionMove[]> = {
${solutionEntries}
};

/** Difficulty scores (total active cells across all solution moves), keyed by puzzle id. */
export const simpleMonoDevDifficulty: Record<number, number> = {
${difficultyEntries}
};
`;
}

const t0 = performance.now();
const puzzles = generate();
const elapsed = (performance.now() - t0).toFixed(0);

puzzles.forEach((p, i) => {
	console.log(
		`  Puzzle ${i + 1}: difficulty=${p.difficulty}  solution=${p.solution
			.map((m) => `T${m.templateIndex}r${m.rotation}`)
			.join('→')}`
	);
});

console.log(`\nTotal generation time: ${elapsed}ms`);

const content = buildFileContent(puzzles);
writeFileSync(outPath, content, 'utf8');
console.log(`\nWrote ${outPath}`);
