import { packs } from '../src/packs.js';
import { distinctPigmentsInTemplate } from '../src/templatePigment.js';
import type { PuzzleConfig, PuzzleTemplate } from '../src/types.js';
import { solveMinMoves } from '../src/PuzzleGenerator.js';
import { findShortestSolution } from '../src/puzzleDifficulty.js';
import { getDistinctRotations, gridToKey } from '../src/puzzleGrid.js';
import { findTemplateContainment } from '../src/templateContainment.js';
import {
	canonicalPuzzleKey,
	isAutoGeneratedPack
} from '../src/puzzleCanonical.js';
import {
	countActiveCells,
	is2x2Shape,
	MIN_TEMPLATE_ACTIVE_CELLS,
	mono2x2TemplateIsFullyFilled
} from '../src/templateShape.js';
import {
	countSolutionGridCoverage,
	minSolutionGridCellsRequired,
	MIN_SOLUTION_GRID_COVERAGE_FRACTION
} from '../src/solutionGridCoverage.js';
import {
	isMultiPigmentPuzzle,
	validateMultiPigmentTemplateCounts
} from '../src/pigmentTemplates.js';
import { canonicalTemplateKey } from '../src/puzzleCanonical.js';
import { packUsesMonoSquareTemplateGeneration } from '../src/packGenerationSpecs.js';

type Severity = 'error' | 'warn';

interface Issue {
	severity: Severity;
	packSlug: string;
	puzzleId: number;
	message: string;
}

function logIssue(issue: Issue) {
	const prefix = issue.severity === 'error' ? '[ERROR]' : '[WARN ]';
	console.log(
		`${prefix} pack="${issue.packSlug}" puzzle=${issue.puzzleId}: ${issue.message}`
	);
}

function hasAllZeroShape(template: PuzzleTemplate): boolean {
	return template.shape.every((row) => row.every((cell) => cell === 0));
}

function findRotationallyEquivalentTemplates(templates: PuzzleTemplate[]): number[][] {
	const buckets = new Map<string, number[]>();

	for (let i = 0; i < templates.length; i++) {
		const t = templates[i];
		const key = canonicalTemplateKey(t);
		const arr = buckets.get(key) ?? [];
		arr.push(i);
		buckets.set(key, arr);
	}

	const groups: number[][] = [];
	for (const indices of buckets.values()) {
		if (indices.length > 1) groups.push(indices);
	}
	return groups;
}

function validateConfig(
	packSlug: string,
	puzzleId: number,
	cfg: PuzzleConfig
): Issue[] {
	const issues: Issue[] = [];
	const n = cfg.startState.length;

	if (n === 0) {
		issues.push({
			severity: 'error',
			packSlug,
			puzzleId,
			message: 'startState grid is empty'
		});
		return issues;
	}

	if (!cfg.startState.every((row) => row.length === n)) {
		issues.push({
			severity: 'error',
			packSlug,
			puzzleId,
			message: 'startState is not square'
		});
	}

	if (cfg.templates.length === 0) {
		issues.push({
			severity: 'warn',
			packSlug,
			puzzleId,
			message: 'no templates defined'
		});
	}

	for (let i = 0; i < cfg.templates.length; i++) {
		const t = cfg.templates[i];
		if (t.shape.length === 0 || t.shape[0].length === 0) {
			issues.push({
				severity: 'error',
				packSlug,
				puzzleId,
				message: `template[${i}] shape is empty`
			});
			continue;
		}

		const rows = t.shape.length;
		const cols = t.shape[0].length;
		if (!t.shape.every((row) => row.length === cols)) {
			issues.push({
				severity: 'error',
				packSlug,
				puzzleId,
				message: `template[${i}] has inconsistent row lengths`
			});
		}

		if (rows > n || cols > n) {
			issues.push({
				severity: 'error',
				packSlug,
				puzzleId,
				message: `template[${i}] (${rows}x${cols}) is larger than puzzle grid ${n}x${n}`
			});
		}

		if (hasAllZeroShape(t)) {
			issues.push({
				severity: 'error',
				packSlug,
				puzzleId,
				message: `template[${i}] has no active cells (all zeros)`
			});
		}

		const activePigments = distinctPigmentsInTemplate(t);
		if (activePigments.length === 0) {
			issues.push({
				severity: 'error',
				packSlug,
				puzzleId,
				message: `template[${i}] has no active cells (no-op)`
			});
		}

		const activeCells = countActiveCells(t.shape);
		if (activeCells < MIN_TEMPLATE_ACTIVE_CELLS) {
			issues.push({
				severity: 'error',
				packSlug,
				puzzleId,
				message: `template[${i}] has ${activeCells} active cell(s); minimum is ${MIN_TEMPLATE_ACTIVE_CELLS}`
			});
		}

		if (
			isAutoGeneratedPack(packSlug) &&
			packUsesMonoSquareTemplateGeneration(packSlug) &&
			is2x2Shape(t.shape) &&
			!mono2x2TemplateIsFullyFilled(t.shape)
		) {
			issues.push({
				severity: 'error',
				packSlug,
				puzzleId,
				message: `template[${i}] is a partial 2×2 mono stencil (${activeCells}/4 cells); auto-generated mono puzzles require a full 2×2`
			});
		}
	}

	if (isMultiPigmentPuzzle(cfg)) {
		const pigmentCheck = validateMultiPigmentTemplateCounts(cfg.templates);
		if (!pigmentCheck.ok) {
			issues.push({
				severity: isAutoGeneratedPack(packSlug) ? 'error' : 'warn',
				packSlug,
				puzzleId,
				message: pigmentCheck.message ?? 'invalid multi-color template distribution'
			});
		}
	}

	const containmentPairs = findTemplateContainment(cfg.templates);
	for (const [inner, outer] of containmentPairs) {
		issues.push({
			severity: 'error',
			packSlug,
			puzzleId,
			message: `template ${inner} is completely contained in template ${outer}`
		});
	}

	const equivGroups = findRotationallyEquivalentTemplates(cfg.templates);
	for (const group of equivGroups) {
		issues.push({
			severity: 'error',
			packSlug,
			puzzleId,
			message: `templates ${group.join(', ')} are identical up to rotation (redundant moves)`
		});
	}

	const solvableDepth = Math.max(
		12,
		cfg.templates.length + (cfg.minMovesToSolve ?? cfg.templates.length) + 2
	);
	const solvable = solveMinMoves(cfg, solvableDepth);
	if (solvable === null) {
		issues.push({
			severity: 'error',
			packSlug,
			puzzleId,
			message: 'no solution found that clears the grid'
		});
	} else {
		const solution = findShortestSolution(cfg, solvableDepth);
		if (solution !== null) {
			const covered = countSolutionGridCoverage(solution, cfg.templates);
			const required = minSolutionGridCellsRequired(n);
			if (covered < required) {
				issues.push({
					severity: 'warn',
					packSlug,
					puzzleId,
					message:
						`shortest solution covers ${covered}/${n * n} grid cells; ` +
						`minimum is ${required} (${MIN_SOLUTION_GRID_COVERAGE_FRACTION * 100}% of the grid)`
				});
			}
		}
	}

	return issues;
}

function validateAutoPackDedup(): Issue[] {
	const issues: Issue[] = [];
	const seen = new Map<string, { packSlug: string; puzzleId: number }>();

	for (const pack of packs) {
		if (!isAutoGeneratedPack(pack.slug)) continue;
		for (const [idStr, cfg] of Object.entries(pack.puzzles)) {
			const puzzleId = Number(idStr);
			const key = canonicalPuzzleKey(cfg);
			const existing = seen.get(key);
			if (existing) {
				issues.push({
					severity: 'error',
					packSlug: pack.slug,
					puzzleId,
					message:
						`duplicate of ${existing.packSlug} #${existing.puzzleId} (canonical key collision)`
				});
			} else {
				seen.set(key, { packSlug: pack.slug, puzzleId });
			}
		}
	}

	return issues;
}

async function main() {
	const allIssues: Issue[] = [];

	for (const pack of packs) {
		for (const [idStr, cfg] of Object.entries(pack.puzzles)) {
			const puzzleId = Number(idStr);
			const issues = validateConfig(pack.slug, puzzleId, cfg);
			for (const issue of issues) {
				allIssues.push(issue);
				logIssue(issue);
			}
		}
	}

	for (const issue of validateAutoPackDedup()) {
		allIssues.push(issue);
		logIssue(issue);
	}

	const errorCount = allIssues.filter((i) => i.severity === 'error').length;
	const warnCount = allIssues.filter((i) => i.severity === 'warn').length;

	if (errorCount === 0 && warnCount === 0) {
		console.log('✅ All packs and puzzles passed validation.');
		process.exit(0);
	} else {
		console.log(`\nValidation complete: ${errorCount} error(s), ${warnCount} warning(s).`);
		process.exit(errorCount === 0 ? 0 : 1);
	}
}

main().catch((err) => {
	console.error('Validation script failed:', err);
	process.exit(1);
});
